# Generated by Django 6.0.2 on 2026-03-08 16:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_adoptionrequest_id_alter_pet_id_favorite'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='adoptionrequest',
            name='family_info',
            field=models.TextField(blank=True, help_text='Tell us about your family members, children, other pets', null=True),
        ),
        migrations.AddField(
            model_name='adoptionrequest',
            name='home_type',
            field=models.CharField(blank=True, choices=[('apartment', 'Apartment'), ('house', 'House'), ('farm', 'Farm'), ('other', 'Other')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='adoptionrequest',
            name='pet_experience',
            field=models.CharField(blank=True, choices=[('first_time', 'First time pet owner'), ('experienced', 'Experienced with pets'), ('multiple_pets', 'Currently have multiple pets'), ('special_needs', 'Experience with special needs pets')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='adoptionrequest',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='adoptionrequest',
            name='pet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pet'),
        ),
        migrations.AlterField(
            model_name='adoptionrequest',
            name='requester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
