# Generated by Django 6.0.2 on 2026-03-08 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_adoptionrequest_family_info_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='contact_email',
            field=models.EmailField(blank=True, help_text='Contact email for inquiries', max_length=254),
        ),
        migrations.AlterField(
            model_name='pet',
            name='contact_phone',
            field=models.CharField(blank=True, help_text='Contact phone number for inquiries', max_length=20),
        ),
    ]
